// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnml-oI8GIJTc0q7zMpsdvBsh7yL733mk',
    appId: '1:898239486823:web:10e5368f34f6cf3f68adc2',
    messagingSenderId: '898239486823',
    projectId: 'bai-1-c11',
    authDomain: 'bai-1-c11.firebaseapp.com',
    storageBucket: 'bai-1-c11.firebasestorage.app',
    measurementId: 'G-5K9H6M30DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6US6B-WtYxyZCzJzO8bgQAXmQS3e1Tx4',
    appId: '1:898239486823:android:8415498ac74a790768adc2',
    messagingSenderId: '898239486823',
    projectId: 'bai-1-c11',
    storageBucket: 'bai-1-c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG5_-ucOLFezTWwCFc8WsSk8qv3W4R330',
    appId: '1:898239486823:ios:233543300eb9ff7d68adc2',
    messagingSenderId: '898239486823',
    projectId: 'bai-1-c11',
    storageBucket: 'bai-1-c11.firebasestorage.app',
    iosBundleId: 'com.example.bai1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG5_-ucOLFezTWwCFc8WsSk8qv3W4R330',
    appId: '1:898239486823:ios:233543300eb9ff7d68adc2',
    messagingSenderId: '898239486823',
    projectId: 'bai-1-c11',
    storageBucket: 'bai-1-c11.firebasestorage.app',
    iosBundleId: 'com.example.bai1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnml-oI8GIJTc0q7zMpsdvBsh7yL733mk',
    appId: '1:898239486823:web:3e2958caf4b5606668adc2',
    messagingSenderId: '898239486823',
    projectId: 'bai-1-c11',
    authDomain: 'bai-1-c11.firebaseapp.com',
    storageBucket: 'bai-1-c11.firebasestorage.app',
    measurementId: 'G-T6LXJXYKBH',
  );
}
