// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMxamBe1gde1WPC8sNgdS5mb3HQLbw0I',
    appId: '1:259532707997:web:af38a5904843be34f29c74',
    messagingSenderId: '259532707997',
    projectId: 'bai-2-firebase',
    authDomain: 'bai-2-firebase.firebaseapp.com',
    storageBucket: 'bai-2-firebase.firebasestorage.app',
    measurementId: 'G-9ZZP437XJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6dLa69bo7K4sycqw-hL9bveQt-Os5GE',
    appId: '1:259532707997:android:f59f1e199f38a6acf29c74',
    messagingSenderId: '259532707997',
    projectId: 'bai-2-firebase',
    storageBucket: 'bai-2-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYCLbpNMDOEWxIyVh8Kwb5s03vgtyqH4',
    appId: '1:259532707997:ios:bbd62d2384f68d61f29c74',
    messagingSenderId: '259532707997',
    projectId: 'bai-2-firebase',
    storageBucket: 'bai-2-firebase.firebasestorage.app',
    iosBundleId: 'com.example.bai2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYCLbpNMDOEWxIyVh8Kwb5s03vgtyqH4',
    appId: '1:259532707997:ios:bbd62d2384f68d61f29c74',
    messagingSenderId: '259532707997',
    projectId: 'bai-2-firebase',
    storageBucket: 'bai-2-firebase.firebasestorage.app',
    iosBundleId: 'com.example.bai2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMxamBe1gde1WPC8sNgdS5mb3HQLbw0I',
    appId: '1:259532707997:web:7cefc98e1caa3dabf29c74',
    messagingSenderId: '259532707997',
    projectId: 'bai-2-firebase',
    authDomain: 'bai-2-firebase.firebaseapp.com',
    storageBucket: 'bai-2-firebase.firebasestorage.app',
    measurementId: 'G-0X9EP2BDM2',
  );
}
